FAMILY_SUPPORT_KEYWORDS = ["AMMI", "ABBA", "MOM", "DAD"]

CATEGORY_KEYWORDS: dict[str, list[str]] = {
    "Eating Out": [
        # Fast food chains
        "MCDONALD",
        "TIM HORTON",
        "STARBUCKS",
        "SUBWAY",
        "POPEYES",
        "POPEYE",
        "WENDY",
        "BURGER KING",
        "KFC",
        "CHIPOTLE",
        "PANDA EXPRESS",
        "FIVE GUYS",
        "CHICK-FIL-A",
        "A&W",
        "HARVEYS",
        "MARY BROWN",
        "CHURCH'S CHICKEN",
        "WINGSTOP",
        # Canadian sit-down / casual dining
        "SWISS CHALET",
        "BOSTON PIZZA",
        "NANDO",
        "MONTANA",
        "KELSEYS",
        "KELSEY",
        "EAST SIDE MARIO",
        "JACK ASTOR",
        "PICKLE BARREL",
        "THE KEG",
        "MILESTONES",
        "MOXIE",
        "EARLS",
        "JOEY",
        "CACTUS CLUB",
        "WHITE SPOT",
        "BIER MARKT",
        "SCORES",
        "ST-HUBERT",
        "THE WORKS",
        "RED LOBSTER",
        "OLIVE GARDEN",
        # Fast-casual
        "FRESHII",
        "PANERA",
        "OSMOW",
        "PITA PIT",
        "MUCHO BURRITO",
        "BURRITO BOYZ",
        "FAT BASTARD",
        "EXTREME PITA",
        "MR SUB",
        "QUIZNOS",
        "FATBURGER",
        "HERO BURGER",
        "SMOKE'S",
        "PARAMOUNT",
        "LAZEEZ",
        "CULTURES",
        "MANCHU WOK",
        "THAI EXPRESS",
        # Breakfast
        "CORA",
        "DENNY",
        "IHOP",
        "WAFFLE",
        # Cuisine-specific keywords
        "PIZZA",
        "SUSHI",
        "RAMEN",
        "PHO",
        "SHAWARMA",
        "TACO",
        "BURRITO",
        "KEBAB",
        "FALAFEL",
        "TANDOORI",
        "BIRYANI",
        "TERIYAKI",
        "WOK",
        "WINGS",
        "GYRO",
        "DONAIR",
        # Delivery / pizza chains
        "DOMINO",
        "PAPA JOHN",
        "PIZZA PIZZA",
        "PANAGO",
        "LITTLE CAESARS",
        # Coffee / juice / bubble tea
        "SECOND CUP",
        "AROMA",
        "BALZAC",
        "CHATIME",
        "GONG CHA",
        "TIGER SUGAR",
        "KUNG FU TEA",
        "COCO BUBBLE",
        "BOOSTER JUICE",
        "JAMBA",
        "JUGO JUICE",
        "SMOOTHIE",
        # Generic descriptors
        "RESTAURANT",
        "CAFE",
        "DINER",
        "GRILL",
        "BISTRO",
        "EATERY",
        "KITCHEN",
        "FOOD COURT",
        "PUB",
        "BAR & GRILL",
    ],
    "Uber Eats": ["UBER EATS", "UBEREATS"],
    "Groceries": [
        # Major Canadian chains
        "METRO",
        "LOBLAWS",
        "NO FRILLS",
        "FOOD BASICS",
        "FRESHCO",
        "SOBEYS",
        "WALMART",
        "COSTCO",
        "T&T",
        "FARM BOY",
        "REAL CANADIAN",
        "SUPERSTORE",
        "FORTINOS",
        "ZEHRS",
        "LONGOS",
        "RABBA",
        "VALUMART",
        "BULK BARN",
        # US / international
        "ALDI",
        "WHOLE FOODS",
        "TRADER JOE",
        # Online grocery
        "VOILA",
        "INSTACART",
        "GROCERY GATEWAY",
        # Generic
        "GROCERY",
        "SUPERMARKET",
        "MARKET",
        # Convenience stores (folded in)
        "7-ELEVEN",
        "CIRCLE K",
        "HASTY MARKET",
        "COUCHE-TARD",
        "ON THE RUN",
        "MACS CONV",
    ],
    "Transportation - Rideshare": ["UBER TRIP", "UBER* TRIP", "UBER *TRIP", "LYFT"],
    "Transportation - Gas": [
        "PETRO",
        "SHELL",
        "ESSO",
        "PIONEER",
        "CANADIAN TIRE GAS",
        "ULTRAMAR",
        "MOBIL",
        "SUNOCO",
        "HUSKY",
        "CHEVRON",
        "COSTCO GAS",
        "CO-OP GAS",
        "DOMO",
    ],
    "Transportation - Parking": ["PARKING", "IMPARK", "GREEN P", "HONK MOBILE"],
    "Transportation - Transit": ["PRESTO", "TTC", "GO TRANSIT", "METROLINX", "TRANSIT"],
    "Shopping": [
        "AMAZON",
        "APPLE.COM",
        "BEST BUY",
        "WINNERS",
        "MARSHALLS",
        "H&M",
        "ZARA",
        "UNIQLO",
        "GAP",
        "OLD NAVY",
        "NIKE",
        "ADIDAS",
        "DOLLARAMA",
        "CANADIAN TIRE",
        "HOME DEPOT",
        "IKEA",
        "SPORT CHEK",
        "INDIGO",
        "CHAPTERS",
        "STAPLES",
        "LULULEMON",
        "ROOTS",
        "SIMONS",
        "THE BAY",
        "HUDSON BAY",
        "SEPHORA",
        "BATH & BODY",
        "MUJI",
        "MINISO",
        "DAISO",
    ],
    "Entertainment": [
        "CINEPLEX",
        "STEAM",
        "PLAYSTATION",
        "XBOX",
        "NINTENDO",
        "AMC",
    ],
    "Subscriptions": [
        "NETFLIX",
        "DISNEY",
        "CRAVE",
        "SPOTIFY",
        "APPLE MUSIC",
        "YOUTUBE",
        "TWITCH",
        "PARAMOUNT+",
        "APPLE TV",
        "PRIME VIDEO",
        "CHATGPT",
        "OPENAI",
        "ADOBE",
        "MICROSOFT 365",
        "GOOGLE STORAGE",
        "ICLOUD",
        "DROPBOX",
        "CLAUDE",
        "ANTHROPIC",
        "NOTION",
        "FIGMA",
        "CANVA",
        "GITHUB",
        "CURSOR",
        "GRAMMARLY",
        "MIDJOURNEY",
    ],
    "Utilities & Telecom": [
        "ROGERS",
        "BELL",
        "TELUS",
        "FIDO",
        "KOODO",
        "VIRGIN MOBILE",
        "FREEDOM MOBILE",
        "HYDRO",
        "ENBRIDGE",
        "ALECTRA",
        "TORONTO HYDRO",
    ],
    "Health & Fitness": [
        "GYM",
        "GOODLIFE",
        "FIT4LESS",
        "LA FITNESS",
        "PLANET FITNESS",
        "PHARMACY",
        "REXALL",
        "SHOPPERS DRUG",
        "DENTIST",
        "DENTAL",
        "CLINIC",
        "MEDICAL",
        "DOCTOR",
        "OPTOMETRIST",
        "PHYSIO",
        "CHIROPRACT",
        "MASSAGE",
        "SALON",
        "BARBER",
        "HAIRCUT",
        "WALK-IN",
        "HOSPITAL",
        "WELLNESS",
        "VITAMIN",
        "GNC",
        "SUPPLEMENT",
    ],
    "Donations": [
        "DONATION",
        "CHARITY",
        "MOSQUE",
        "MASJID",
        "TEMPLE",
        "CHURCH",
        "ISLAMIC",
        "ZAKAT",
        "SADAQAH",
        "RED CROSS",
        "SALVATION ARMY",
        "UNITED WAY",
    ],
    "Investment": ["QUESTRADE", "WEALTHSIMPLE", "INTERACTIVE BROKERS", "TD DIRECT"],
    "Internal Transfer": ["INTERNET TRANSFER", "TRANSFER OUT", "TRANSFER IN", "E-TRANSFER SENT"],
}

SKIP_PATTERNS = ["PAYMENT THANK YOU", "PAYMENT - THANK YOU", "THANK YOU"]


def categorize_transaction(description: str, family_recipients: list[str] | None = None) -> str:
    upper = description.upper()

    # Check for family support e-transfers first
    if family_recipients:
        for recipient in family_recipients:
            if recipient.upper() in upper:
                return "Family Support"

    # Check for skip patterns (these should still be categorized but might be filtered)
    for pattern in SKIP_PATTERNS:
        if pattern in upper:
            return "Credit Card Payment"

    # Uber disambiguation
    if "UBER" in upper:
        if "EATS" in upper:
            return "Uber Eats"
        if "ONE" in upper or "PASS" in upper:
            return "Subscriptions"
        return "Transportation - Rideshare"

    # Shoppers Drug Mart disambiguation — pharmacy, not groceries
    if "SHOPPERS" in upper and "DRUG" in upper:
        return "Health & Fitness"

    # Match against keyword categories
    for category, keywords in CATEGORY_KEYWORDS.items():
        for keyword in keywords:
            if keyword in upper:
                return category

    return "Other"
