"""add name housing financial_plan

Revision ID: 69336c3d2f2b
Revises: 3ffcf08cb268
Create Date: 2026-03-03 03:45:43.880604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69336c3d2f2b'
down_revision: Union[str, None] = '3ffcf08cb268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('housing_situation', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('financial_plan', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('user_profiles', 'financial_plan')
    op.drop_column('user_profiles', 'housing_situation')
    # ### end Alembic commands ###
